package com.guochang.greendaodemo.db.entity;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table game_level.
 */
public class GameLevel {

    private Long id;
    private int gameType;
    private int level;
    private Integer sumCount;
    private Integer rightCount;
    private String reserve;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public GameLevel() {
    }

    public GameLevel(Long id) {
        this.id = id;
    }

    public GameLevel(Long id, int gameType, int level, Integer sumCount, Integer rightCount, String reserve) {
        this.id = id;
        this.gameType = gameType;
        this.level = level;
        this.sumCount = sumCount;
        this.rightCount = rightCount;
        this.reserve = reserve;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public int getGameType() {
        return gameType;
    }

    public void setGameType(int gameType) {
        this.gameType = gameType;
    }

    public int getLevel() {
        return level;
    }

    public void setLevel(int level) {
        this.level = level;
    }

    public Integer getSumCount() {
        return sumCount;
    }

    public void setSumCount(Integer sumCount) {
        this.sumCount = sumCount;
    }

    public Integer getRightCount() {
        return rightCount;
    }

    public void setRightCount(Integer rightCount) {
        this.rightCount = rightCount;
    }

    public String getReserve() {
        return reserve;
    }

    public void setReserve(String reserve) {
        this.reserve = reserve;
    }

    // KEEP METHODS - put your custom methods here
    public GameLevel(int gameType, int level, Integer sumCount, Integer rightCount) {
        this.gameType = gameType;
        this.level = level;
        this.sumCount = sumCount;
        this.rightCount = rightCount;
    }
    // KEEP METHODS END

}
