package com.guochang.greendaodemo.db.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.guochang.greendaodemo.db.entity.AppProperty;
import com.guochang.greendaodemo.db.entity.GameLevel;

import com.guochang.greendaodemo.db.dao.AppPropertyDao;
import com.guochang.greendaodemo.db.dao.GameLevelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig appPropertyDaoConfig;
    private final DaoConfig gameLevelDaoConfig;

    private final AppPropertyDao appPropertyDao;
    private final GameLevelDao gameLevelDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        appPropertyDaoConfig = daoConfigMap.get(AppPropertyDao.class).clone();
        appPropertyDaoConfig.initIdentityScope(type);

        gameLevelDaoConfig = daoConfigMap.get(GameLevelDao.class).clone();
        gameLevelDaoConfig.initIdentityScope(type);

        appPropertyDao = new AppPropertyDao(appPropertyDaoConfig, this);
        gameLevelDao = new GameLevelDao(gameLevelDaoConfig, this);

        registerDao(AppProperty.class, appPropertyDao);
        registerDao(GameLevel.class, gameLevelDao);
    }
    
    public void clear() {
        appPropertyDaoConfig.getIdentityScope().clear();
        gameLevelDaoConfig.getIdentityScope().clear();
    }

    public AppPropertyDao getAppPropertyDao() {
        return appPropertyDao;
    }

    public GameLevelDao getGameLevelDao() {
        return gameLevelDao;
    }

}
